#define LEDS_NUMBER    0
#define BUTTONS_NUMBER 1

#define BUTTON_START   30
#define BUTTON_1       30
#define BUTTON_STOP    30

#define BUTTON_1_PULL   NRF_GPIO_PIN_PULLUP
#define BUTTON_1_SENSE  NRF_GPIO_PIN_SENSE_LOW
#define BUTTON_1_VALUE  0
#define BUTTON_1_ISTOUCH 1

#define MOTOR_PIN 25
#define MOTOR_ON 1

#define POWER_PIN 2
#define POWER_ON 1
#define POWER_PULL NRF_GPIO_PIN_NOPULL
#define POWER_SENSE NRF_GPIO_PIN_NOSENSE
