// LEDs definitions 
#define LEDS_NUMBER    0
#define BUTTONS_NUMBER 1

#define BUTTON_START   8
#define BUTTON_1       8
#define BUTTON_STOP    8

#define BUTTON_1_PULL	NRF_GPIO_PIN_PULLDOWN
#define BUTTON_1_VALUE	1
#define BUTTON_1_SENSE	NRF_GPIO_PIN_SENSE_HIGH
#define BUTTON_1_ISTOUCH 1

#define MOTOR_PIN 6
#define MOTOR_ON 1

#define POWER_PIN 24
#define POWER_ON 1
#define POWER_PULL NRF_GPIO_PIN_NOPULL
#define POWER_SENSE NRF_GPIO_PIN_NOSENSE
